from typing import Tuple


def verify(input_file: str, output_file: str) -> Tuple[bool, str]:
    """
    Verification function: checks if all the constraints are satisfied.
    Please do NOT change the function name and arguments.
    It is used by the agent to verify the output of the solver.

    Args:
        input_file: Path to the input file
        output_file: Path to the output file generated by the solver

    Returns:
        Tuple[bool, str]: A tuple of (is_valid, error_message)
        is_valid: True if the output is valid, False otherwise
        error_message: If the output is invalid, please provide a detailed error message on why it is invalid;
        If the output is valid, please return an empty string.

    """
    # inputs = parse_input(input_file)
    # outputs = parse_output(output_file)
    raise NotImplementedError("This is a placeholder implementation.")
